Emit Glue Schema Registry usage metrics
awslabs/amazon-kinesis-client pull request #855
Opened 2021-09-22 06:48 UTC by blacktooth

*Description of changes:*

Sets the User Agent for the de-serializer to "kcl". This enables the underlying Glue Schema Registry library to emit UserAgent metrics.

*Testing*

Build successful.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-09-29 23:06 UTC, joshua-kim commented on amazon-kinesis-client/src/main/java-templates/KinesisConsumerLibraryPackage.java
> +public final class KinesisConsumerLibraryPackage {
nit: Can we call this `KinesisClientLibraryPackage` instead?

2021-09-29 23:10 UTC, joshua-kim requested changes
Left a minor nit.

2021-09-29 23:10 UTC, joshua-kim approved these changes
LGTM

2021-09-29 23:12 UTC, joshua-kim commented on amazon-kinesis-client/pom.xml
> +      <!-- Required for generating maven version as a Java class for runtime access -->
Really cool plugin!

2021-09-30 01:29 UTC, shanmsac approved these changes
no comments, approving.

2021-09-30 12:05 UTC, merged